preset: laravel

risky: false

enabled:
  - concat_with_spaces

disabled:
  - concat_without_spaces
  - blank_line_after_opening_tag
  - short_array_syntax

finder:
  exclude:
    - "tests"
  name:
    - "*.php"
